services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_php
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/
    depends_on:
      - postgres
      - elasticsearch
      - elasticsearch2
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:latest
    container_name: app_postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: app_elasticsearch1
    environment:
      - node.name=es-node-1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/esdata/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  elasticsearch2:
    image: elasticsearch:7.17.12
    container_name: app_elasticsearch2
    environment:
      - node.name=es-node-2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/esdata/esdata2:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.12
    container_name: app_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      XPACK_ENCRYPTED_SAVED_OBJECTS_ENCRYPTIONKEY: "devtestkey1234567890"
    depends_on:
      - elasticsearch
      - elasticsearch2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmqdata:
