services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_php
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/
    depends_on:
      - postgres
      - elasticsearch
      - elasticsearch2
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./app:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:latest
    container_name: app_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: app_elasticsearch1
    env_file:
      - .env
    environment:
      - node.name=es-node-1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_DIR}esdata1:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH1_PORT}:9200"

  elasticsearch2:
    image: elasticsearch:7.17.12
    container_name: app_elasticsearch2
    environment:
      - node.name=es-node-2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=es-node-1,es-node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_DATA_DIR}esdata2:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH2_PORT}:9200"

  kibana:
    image: kibana:7.17.12
    container_name: app_kibana
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      XPACK_ENCRYPTED_SAVED_OBJECTS_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
    depends_on:
      - elasticsearch
      - elasticsearch2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ${RABBITMQ_DATA_DIR}:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitmqdata:
